heat_template_version: queens

parameters:


  vn_name: 
    type: string
    default: "admin_domain:admin:right-net"

  management_vn_name: 
    type: string
    default: "admin_domain:admin:management-net"

  sec_group:
    type: string      
    default: "admin_domain:admin:test-sec-group"

  instance_ip:
    type: string 
    default: "10.10.1.3"

  management_ip:
    type: string 
    default: "172.16.100.4"

  instance_name:
    type: string 
    default: "right-vn-vm1"

  image_name:
    type: string 
    default: "ubuntu"

  flavor_name:
    type: string
    default: xp.m1.small
 
  az: 
    type: string
    default: "nova:compute-2"

  cloud_init_string:
    type: string
    default: |
       #cloud-config
        chpasswd:
          list: |
            ubuntu:mypasswd
          expire: False
        ssh_pwauth: True
        users:
          - name: 'ubuntu'
            ssh-authorized-keys:
              - '

  ssh_pub_key:
    type: string

resources:
  cloud_init:
    type: OS::Heat::SoftwareConfig
    properties:
      group: ungrouped
      config:  {list_join: [' ', [ {get_param: cloud_init_string}, {get_param: ssh_pub_key}, "'"]]}
 
  vmi_instance:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_network_refs:  [{ get_param: vn_name }]
      port_security_enabled: true
      security_group_refs: [{ get_param: sec_group }]

  vmi_management_instance:
    type: OS::ContrailV2::VirtualMachineInterface
    properties:
      virtual_network_refs:  [{ get_param: management_vn_name }]
      port_security_enabled: true
      security_group_refs: [{ get_param: sec_group }]

  vmi_instance_ip:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ vmi_instance ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: vmi_instance }]
      virtual_network_refs: [{ get_param: vn_name }]
      instance_ip_address: { get_param: instance_ip }
 
  vmi_management_ip:
    type: OS::ContrailV2::InstanceIp
    depends_on: [ vmi_management_instance ]
    properties:
      virtual_machine_interface_refs: [{ get_resource: vmi_management_instance }]
      virtual_network_refs: [{ get_param: management_vn_name }]
      instance_ip_address: { get_param: management_ip }

  instance:
    type: OS::Nova::Server
    depends_on: [vmi_instance_ip, vmi_management_ip]
    properties:
      name: { get_param: instance_name }
      image: { get_param: image_name }
      flavor: { get_param: flavor_name }
      availability_zone: { get_param: az }
      user_data_format: RAW
      config_drive: true
      user_data: { get_resource: cloud_init }
      networks: 
       - port: { get_resource: vmi_instance }
       - port: { get_resource: vmi_management_instance }


